### ISSUE TITLE
Improve competition validation track

### ISSUE THREAD

**Issue by Gamenot** [huawei-noah/SMARTS#1732]
Validation track should just test that a policy can accept all shapes of observation (e.g. 0 length waypoint arrays)

**Comment by Gamenot** [comment]
I could see that modelled as:

`scl benchmark validate <benchmark> <agent_locator>`
`scl benchmark run --skip-validation <benchmark> <agent_locator>`

Then the benchmark listing looks like:
```yaml
# smarts/benchmark/benchmark_listing.yaml
---
benchmarks:
  driving_smarts:
    name: "Driving SMARTS"
    versions:
      -
        version: 0.0
        entrypoint: "smarts.benchmark.entrypoints.benchmark_runner_v0.benchmark_from_configs"
        validation_entrypoint: "smarts.benchmark.entrypoints.benchmark_runner_v0.validate_agent"
```
