### ISSUE TITLE
Traffic Histories interface bug and scalability

### ISSUE THREAD

**Issue by sah-huawei** [huawei-noah/SMARTS#732]
**High Level Description**
When a large traffic history dataset (like NGSIM) is used, a few issues are revealed, including samples being missed (the bug).  This is needed to support large-scale imitation learning.

**SMARTS version**
0.4.15

**Previous associated issues**
#402 #407 #596 #640 #226 etc.

**Description of Problems**
Traffic history files are currently supplied in a json format, which wastes a lot of space (e.g. redundantly specifying each field name for each vehicle at each timestep) and also time (having to be _entirely_  read through and parsed on every single batch query, roughy per every 300 entries in the file, even if it's not all kept in memory ).  This slows down Smarts considerably on traffic history playback and isn't scalable.

Further, If entries are out of order in the batches (which we cannot easily/efficiently prevent with the current json-to-dictionary parsing) the provider will miss entries when it queries for them at a time if they don't fit into our "two batch" window that we keep in memory.  I am experiencing this with the NGSIM traffic history dataset for i80.

**Plan**
- Change the supported traffic history file format to a `sqlite` database file instead of json
    - Update and checkin the dataset conversion script(s) to generate this format instead of json
    - Update `traffic_history_provider.py` to query this (instead of the `trafffic_history_service`) to:
        - get all unique vehicles and infer their missions (start time+position) at the beginning of the simulation
        - get which vehicles changed at each timestep
- (Possibly) Support multiple (keyed) histories in the same database file (instead of supporting a list of history filenames)
- Provide a script to convert any existing json history files to sqlite3

**Comment by sah-huawei** [comment]
FYI @zbzhu99

**Comment by sah-huawei** [comment]
As described above and  in PR #741, we have moved away from JSON for our traffic history files.  The new format used by SMARTS has a `.shf` extension (for "SMART history file") with much smaller files.  These files are discovered automatically by SMARTS within the `scenario` folder.

Each traffic history dataset has a corresponding "spec" which is a new YAML file users can provide to describe parameters related to the conversion and importation of original NGSIM or INTEACTION data into an `.shf` file.  This conversion happens when a scenario is built and obsoletes the need to use separate conversion scripts (like `tools/interaction_dataset_converter.py).

Unless the `--clean` parameter is passed to `scl scenario build`, the creation of the `.shf` file only happens once.

So, for example, whereas before the traffic history `.json` files were passed to `gen_scenario()` in `scenario.py`, now a `.yaml` file would be passed instead, like:
```python
gen_scenario(
    t.Scenario(
        traffic_histories=["i80-0400.yaml", "i80-0500.yaml"],
    ),
    output_dir=Path(__file__).parent,
)
```

We also maintain the ability to convert the now-obsolete `.json` files into `.shf` files if the  `traffic_histories` list still contains any.  However, it's recommended to start using `.yaml` files going forward.  (And indeed, these are required for importation of NGSIM data since it needs to be scaled and flipped anyway, cf. issue #407.)

I've tested this with both NGSIM and INTERACTION data, where the YAML files looked like:

For some INTERACTION data, `traffic_history_000.yaml`:
```yaml
trajectory_dataset:                                                                                                                                             
    name: traffic_history_000
    source: INTERACTION
    input_path: ./interaction/vehicle_tracks_000.csv
 
    # 55mph is roughly 25m/s.  100km/h is roughly 28m/s.
    speed_limit_mps: 15
```

and

For some NGSIM data, `i80_400.yaml`:
```yaml
trajectory_dataset:                                                                                                                                             
    name: i80_0400-0415
    source: NGSIM
    input_path: ./ngsim/xy-trajectories/i80/trajectories-0400-0415.txt
 
    # US highway lanes are about 12 feet (or ~3.7m) wide
    real_lane_width_m: 3.6576
    # 55mph is roughly 25m/s.  100km/h is roughly 28m/s.
    speed_limit_mps: 28
 
    flip_y: True
    swap_xy: True
 
    x_offset_px: 470
 
    map_net:
        # These are dimensions of the Sumo network in map.net.xml.
        # We map the coordinates in the input dataset onto this space.
        # max_y is required if flip_y since True.
        max_y: 228
 
        # The map width is used to filter position_x values
        # to ensure they're in range.
        width: 2040.15
 
        # lane_width is used to figure out the map scale,
        # which is lane_width / real_lane_width_m.
        # (So use `real_lane_width_m` here for 1:1 scale.)
        # It's also used in SMARTS for detecting off-road, etc.
        # Note that the lane_width is only about 24 *on* *average* here.
        # It varies between 23.5 and 26 in map.net.xml.
        lane_width: 24.15
```

Note that the `input_path` points to wherever the original data that's to be converted and imported resides and is the most important part of the yaml file.  

`speed_limit` is just for convenience and is now used by `history_vehicles_replacement_for_imitation_learning.py` as the default speed for each agent that's added to the simulation amongst the traffic.  (This is because the traffic in NGSIM is going faster than in INTERACTION datasets, and the agent would immediately get rear-ended otherwise.)

`lane_width` gives the ability to support different scales for `map.net.xml`.  For example, the `map.net.xml` file currently associated with the NGSIM `i80` dataset  uses lanes that are ~24 pixels wide, as opposed to the normal 1:1-scaled width of ~3.7 in the INTERACTION map.
